name: nsidc-miz-analysis
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  - basemap
  - basemap-data-hires
  - ffmpeg
  - geopandas
  - joblib
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - rasterio
